#!/bin/bash
# knscale
# By Tedezed

# Kuberentes scale all in namespace

#TYPE='deploy'
TYPE=$1
REPLICAS=$2
NAMESPACE=$3

for k8s_deploy in $(kubectl get $TYPE -n $NAMESPACE | awk '{ print $1}' | grep -v NAME); do
    kubectl scale $TYPE --replicas=$REPLICAS $k8s_deploy -n $NAMESPACE
done