#!/bin/bash
# ksecret
# By Tedezed

# See secret data
SECRET_NAME=$1
NAMESPACE=$2
for k in $(kubectl get secret $SECRET_NAME -n $NAMESPACE -o json | jq ".data | keys[]" | tr -d '"')
do
    echo "Secret $k: $(kubectl get secret $SECRET_NAME -n $NAMESPACE -o json | jq ".data.\"$k\"" | tr -d '"' | base64 --decode)"
done