#!/bin/bash
# By Tedezed
# For Cloud Cementery

cat <<EOF
Usage gcloud_kill_disk -i disk_origin -z europe-west1-b -l europe-west1
    -i : Input disk
    -z : Zone
    -l : Location
    -h : help
EOF
exit 2
}

while getopts ":i:o:z:l:h" OPTIONS; do
    case "${OPTIONS}" in
        i) INPUT=${OPTARG} ;;
        z) ZONE=${OPTARG} ;;
        l) LOCATION=${OPTARG} ;;
        h) usage ;;
        *) usage ;;
    esac
done

gcloud compute disks snapshot ${INPUT} --zone ${ZONE} --snapshot-names dead-${INPUT} \
    --storage-location=${LOCATION} --labels funeral-home=true
gcloud compute disks delete ${INPUT} --zone ${ZONE}